# Generated by Django 4.2 on 2024-01-02 02:04

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portal",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "blocks",
                    wagtail.fields.StreamField(
                        [
                            (
                                "banner",
                                wagtail.blocks.StreamBlock(
                                    [
                                        (
                                            "banner",
                                            wagtail.blocks.StructBlock(
                                                [
                                                    (
                                                        "image",
                                                        wagtail.images.blocks.ImageChooserBlock(
                                                            label="배너"
                                                        ),
                                                    ),
                                                    (
                                                        "fit_container",
                                                        wagtail.blocks.BooleanBlock(
                                                            label="container에 맞추기",
                                                            required=False,
                                                        ),
                                                    ),
                                                    (
                                                        "title",
                                                        wagtail.blocks.CharBlock(
                                                            label="제목"
                                                        ),
                                                    ),
                                                    (
                                                        "content",
                                                        wagtail.blocks.RichTextBlock(
                                                            label="에디터", required=False
                                                        ),
                                                    ),
                                                    (
                                                        "html",
                                                        wagtail.blocks.RawHTMLBlock(
                                                            label="HTML", required=False
                                                        ),
                                                    ),
                                                ],
                                                label="배너",
                                                required=False,
                                            ),
                                        )
                                    ],
                                    collapsed=True,
                                    heading="배너",
                                ),
                            ),
                            (
                                "richtext",
                                wagtail.blocks.RichTextBlock(
                                    label="에디터", required=False
                                ),
                            ),
                            (
                                "html",
                                wagtail.blocks.RawHTMLBlock(
                                    label="HTML 코드", required=False
                                ),
                            ),
                            (
                                "notice",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "tag",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[], label="태그"
                                            ),
                                        ),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                label="제목", required=True
                                            ),
                                        ),
                                        (
                                            "sub_title",
                                            wagtail.blocks.CharBlock(
                                                label="부제목", required=False
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="이미지", required=False
                                            ),
                                        ),
                                    ],
                                    label="알림",
                                ),
                            ),
                            (
                                "news",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "tag",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[], label="태그"
                                            ),
                                        ),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                label="제목", required=True
                                            ),
                                        ),
                                        (
                                            "sub_title",
                                            wagtail.blocks.CharBlock(
                                                label="부제목", required=False
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="이미지", required=False
                                            ),
                                        ),
                                    ],
                                    label="뉴스",
                                ),
                            ),
                            (
                                "blog",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "tag",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[], label="태그"
                                            ),
                                        ),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                label="제목", required=True
                                            ),
                                        ),
                                        (
                                            "sub_title",
                                            wagtail.blocks.CharBlock(
                                                label="부제목", required=False
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="이미지", required=False
                                            ),
                                        ),
                                    ],
                                    label="블로그",
                                ),
                            ),
                            (
                                "popup",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "tag",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[], label="태그"
                                            ),
                                        ),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                label="제목", required=True
                                            ),
                                        ),
                                        (
                                            "sub_title",
                                            wagtail.blocks.CharBlock(
                                                label="부제목", required=False
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="이미지", required=False
                                            ),
                                        ),
                                    ],
                                    label="팝업",
                                ),
                            ),
                            (
                                "policy",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "tag",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[], label="태그"
                                            ),
                                        ),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                label="제목", required=True
                                            ),
                                        ),
                                        (
                                            "sub_title",
                                            wagtail.blocks.CharBlock(
                                                label="부제목", required=False
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="이미지", required=False
                                            ),
                                        ),
                                    ],
                                    label="이용 규정",
                                ),
                            ),
                            (
                                "partner",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "tag",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[], label="태그"
                                            ),
                                        ),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                label="제목", required=True
                                            ),
                                        ),
                                        (
                                            "sub_title",
                                            wagtail.blocks.CharBlock(
                                                label="부제목", required=False
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="이미지", required=False
                                            ),
                                        ),
                                    ],
                                    label="파트너",
                                ),
                            ),
                            (
                                "program",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "tag",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[], label="태그"
                                            ),
                                        ),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                label="제목", required=True
                                            ),
                                        ),
                                        (
                                            "sub_title",
                                            wagtail.blocks.CharBlock(
                                                label="부제목", required=False
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="이미지", required=False
                                            ),
                                        ),
                                    ],
                                    label="프로그램",
                                ),
                            ),
                            (
                                "survey",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "tag",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[], label="태그"
                                            ),
                                        ),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                label="제목", required=True
                                            ),
                                        ),
                                        (
                                            "sub_title",
                                            wagtail.blocks.CharBlock(
                                                label="부제목", required=False
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="이미지", required=False
                                            ),
                                        ),
                                    ],
                                    label="설문조사",
                                ),
                            ),
                            (
                                "catalog",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "tag",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[], label="태그"
                                            ),
                                        ),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                label="제목", required=True
                                            ),
                                        ),
                                        (
                                            "sub_title",
                                            wagtail.blocks.CharBlock(
                                                label="부제목", required=False
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="이미지", required=False
                                            ),
                                        ),
                                    ],
                                    label="카탈로그",
                                ),
                            ),
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                        verbose_name="블록",
                    ),
                ),
                (
                    "footer",
                    wagtail.fields.StreamField(
                        [
                            (
                                "richtext",
                                wagtail.blocks.RichTextBlock(
                                    label="에디터", required=False
                                ),
                            ),
                            (
                                "html",
                                wagtail.blocks.RawHTMLBlock(
                                    label="HTML 코드", required=False
                                ),
                            ),
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                        verbose_name="푸터",
                    ),
                ),
            ],
            options={
                "verbose_name": "포털",
                "verbose_name_plural": "포털",
            },
            bases=("wagtailcore.page",),
        ),
    ]
