version: "3"
services:
  db:
    image: postgres
    container_name: edx_operation.db
    environment:
      POSTGRES_DB: edx_operation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - devstack_default
    volumes:
      - edx_operation_postgresql:/var/lib/postgresql/data

  # memcache:
  #   image: memcached:1.4.24
  #   container_name: edx_operation.memcache

  app:
    # Uncomment this line to use the official edx_operation base image
    # image: openedx/edx_operation
    build:
      context: .
      target: dev

    container_name: edx_operation.app
    volumes:
      - .:/edx/app/edx-operation/
    command: bash -c 'while true; do python /edx/app/edx-operation/manage.py runserver 0.0.0.0:34013; sleep 2; done'
    environment:
      DJANGO_SETTINGS_MODULE: edx_operation.settings.devstack
      DB_NAME: edx_operation
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "34013:34013" # TODO: change this to your port
    networks:
      - devstack_default
    depends_on:
      - db

networks:
  devstack_default:
    external: true

volumes:
  edx_operation_postgresql:
