# Generated by Django 4.2 on 2023-12-25 18:24

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import taggit.managers
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.search.index


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("student", "0001_initial"),
        ("wagtail_common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="활성")),
                (
                    "title",
                    models.CharField(db_index=True, max_length=254, verbose_name="제목"),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            (
                                "image",
                                wagtail.images.blocks.ImageChooserBlock(
                                    label="이미지", required=False
                                ),
                            ),
                            (
                                "richtext",
                                wagtail.blocks.RichTextBlock(
                                    label="텍스트", required=False
                                ),
                            ),
                            (
                                "embed",
                                wagtail.embeds.blocks.EmbedBlock(
                                    label="임베드", required=False
                                ),
                            ),
                            (
                                "html",
                                wagtail.blocks.RawHTMLBlock(
                                    help_text="html 코드를 입력할 수 있습니다.",
                                    label="HTML",
                                    required=False,
                                ),
                            ),
                        ],
                        use_json_field=True,
                        verbose_name="내용",
                    ),
                ),
                (
                    "version",
                    models.CharField(default="1.0.0", max_length=10, verbose_name="버전"),
                ),
                (
                    "mandatory",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="동의 필수 사항"
                    ),
                ),
                (
                    "ordering",
                    models.SmallIntegerField(
                        db_index=True, default=1, verbose_name="화면 정렬 순서"
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="wagtail_common.Tagging",
                        to="wagtail_common.Tag",
                        verbose_name="태그",
                    ),
                ),
            ],
            options={
                "verbose_name": "이용 규정",
                "verbose_name_plural": "이용 규정",
                "ordering": ("ordering",),
                "unique_together": {("title", "version")},
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name="PolicyConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("has_consented", models.BooleanField(default=True, verbose_name="동의")),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="policy.policy",
                        verbose_name="이용 규정",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                        verbose_name="학습자",
                    ),
                ),
            ],
            options={
                "verbose_name": "이용 규정 동의",
                "verbose_name_plural": "이용 규정 동의",
            },
        ),
    ]
