# Generated by Django 4.2 on 2024-01-02 02:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import edx_operation.apps.core.utils.common
import edx_operation.apps.course.models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    opaque_keys.edx.django.models.UsageKeyField(
                        max_length=255, primary_key=True, serialize=False
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("sequence", models.SmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "섹션",
                "verbose_name_plural": "섹션",
                "ordering": ("courserun", "sequence"),
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        default=edx_operation.apps.course.models.random_number,
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="과정 코드",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(db_index=True, max_length=255, verbose_name="제목"),
                ),
                (
                    "cover",
                    models.ImageField(
                        max_length=255,
                        upload_to=edx_operation.apps.core.utils.common.upload_unique_name,
                        verbose_name="커버 이미지",
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="활성")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="설명"),
                ),
                ("target", models.TextField(blank=True, null=True, verbose_name="대상")),
                (
                    "objective",
                    models.TextField(blank=True, null=True, verbose_name="학습목표"),
                ),
                (
                    "grading",
                    models.TextField(blank=True, null=True, verbose_name="평가 방법"),
                ),
                (
                    "created_date",
                    models.DateField(blank=True, null=True, verbose_name="출시"),
                ),
                (
                    "preview",
                    models.URLField(blank=True, null=True, verbose_name="미리보기"),
                ),
                (
                    "contents",
                    models.TextField(blank=True, null=True, verbose_name="목차"),
                ),
                (
                    "effort",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="학습 시간"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="레벨"
                    ),
                ),
                (
                    "ncs_unit",
                    models.CharField(
                        blank=True, max_length=254, null=True, verbose_name="NCS 분류"
                    ),
                ),
            ],
            options={
                "verbose_name": "과정",
                "verbose_name_plural": "과정",
            },
        ),
        migrations.CreateModel(
            name="Subsection",
            fields=[
                (
                    "id",
                    opaque_keys.edx.django.models.UsageKeyField(
                        max_length=255, primary_key=True, serialize=False
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("sequence", models.SmallIntegerField(default=0)),
                ("format", models.CharField(blank=True, max_length=50, null=True)),
                ("lms_web_url", models.URLField(max_length=1000)),
                ("student_view_url", models.URLField(max_length=1000)),
                ("is_special_exam", models.BooleanField(default=False)),
                ("weight", models.FloatField(default=0)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="course.chapter"
                    ),
                ),
            ],
            options={
                "verbose_name": "차시",
                "verbose_name_plural": "차시",
                "ordering": ("chapter", "sequence"),
            },
        ),
        migrations.CreateModel(
            name="CourseRun",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    opaque_keys.edx.django.models.CourseKeyField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="회차 코드",
                    ),
                ),
                (
                    "run_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="회차 번호"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(db_index=True, max_length=255, verbose_name="제목"),
                ),
                (
                    "enrollment_start",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="등록 시작"
                    ),
                ),
                (
                    "enrollment_end",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="등록 종료"
                    ),
                ),
                (
                    "start",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="시작"
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="종료"
                    ),
                ),
                (
                    "invitation_only",
                    models.BooleanField(default=True, verbose_name="자율등록 허용 안함"),
                ),
                (
                    "visible_to_staff_only",
                    models.BooleanField(default=False, verbose_name="학습자에게 비공개"),
                ),
                (
                    "certificate_available_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="수료증 발급"),
                ),
                (
                    "pacing",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="학습 방법",
                    ),
                ),
                ("grading", models.JSONField(default=dict, verbose_name="평가 방법")),
                (
                    "verification_method",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="본인 인증 방법"
                    ),
                ),
                (
                    "entrance_id_verification",
                    models.BooleanField(default=True, verbose_name="입과 시 인증"),
                ),
                (
                    "course_verification",
                    models.BooleanField(
                        default=True, verbose_name="매 8차시 진행, 진행평가, 시험, 과제 학습 시 인증"
                    ),
                ),
                (
                    "study_in_order",
                    models.BooleanField(default=True, verbose_name="순차 학습 적용"),
                ),
                (
                    "daily_study_limit",
                    models.IntegerField(
                        default=8,
                        help_text="0: 제한 하지 않습니다.",
                        verbose_name="일일 학습 제한 차시",
                    ),
                ),
                (
                    "block_multiple_window",
                    models.BooleanField(default=True, verbose_name="동시 학습 창 제한"),
                ),
                (
                    "exam_prerequisite_progress",
                    models.IntegerField(default=80, verbose_name="시험/과제 응시 진도 조건 %"),
                ),
                (
                    "exam_prerequisite_midterm_exam",
                    models.BooleanField(
                        default=True, verbose_name="시험/과제 응시 진행평가 완료 조건"
                    ),
                ),
                (
                    "block_exam_on_mobile",
                    models.BooleanField(default=True, verbose_name="시험/과제 응시 모바일 제한"),
                ),
                (
                    "block_exam_on_tablet",
                    models.BooleanField(default=True, verbose_name="시험/과제 응시 태블릿 제한"),
                ),
                (
                    "exam_reattempt_days",
                    models.IntegerField(
                        default=0, help_text="0: 허용하지 않음", verbose_name="재시험 허용 일"
                    ),
                ),
                (
                    "ignore_certificate_available_date",
                    models.BooleanField(default=False, verbose_name="수료증 발급 날짜 무시"),
                ),
                (
                    "pass_on_progress",
                    models.IntegerField(default=0, verbose_name="진도율로 수료 처리"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.course",
                        verbose_name="과정",
                    ),
                ),
            ],
            options={
                "verbose_name": "회차",
                "verbose_name_plural": "회차",
                "unique_together": {("course", "run_number")},
            },
        ),
        migrations.CreateModel(
            name="CourseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "org",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="분류"
                    ),
                ),
                (
                    "course_document",
                    models.FileField(
                        max_length=255,
                        upload_to=edx_operation.apps.core.utils.common.upload_unique_name,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["xlsx", "xls"]
                            )
                        ],
                        verbose_name="과정 개요서",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        max_length=255,
                        upload_to=edx_operation.apps.core.utils.common.upload_unique_name,
                        verbose_name="커버 이미지",
                    ),
                ),
                (
                    "time_document",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=edx_operation.apps.core.utils.common.upload_unique_name,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["xlsx", "xls"]
                            )
                        ],
                        verbose_name="학습 시간 계획서",
                    ),
                ),
                (
                    "content_document",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=edx_operation.apps.core.utils.common.upload_unique_name,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["xlsx", "xls"]
                            )
                        ],
                        verbose_name="콘텐츠 경로 문서",
                    ),
                ),
                (
                    "course",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="course.course",
                        verbose_name="과정",
                    ),
                ),
            ],
            options={
                "verbose_name": "과정 개요서",
                "verbose_name_plural": "과정 개요서",
            },
        ),
        migrations.AddField(
            model_name="chapter",
            name="courserun",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.courserun"
            ),
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    opaque_keys.edx.django.models.UsageKeyField(
                        max_length=255, primary_key=True, serialize=False
                    ),
                ),
                ("block_type", models.CharField(db_index=True, max_length=100)),
                ("display_name", models.CharField(max_length=255)),
                ("lms_web_url", models.URLField(max_length=1000)),
                ("student_view_url", models.URLField(max_length=1000)),
                (
                    "subsection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.subsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "블록",
                "verbose_name_plural": "블록",
            },
        ),
    ]
