# Generated by Django 3.2.20 on 2023-08-06 19:57

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationEventError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('event_type', models.CharField(db_index=True, max_length=255)),
                ('event_time', models.DateTimeField()),
                ('error', models.TextField()),
                ('source_data', models.TextField()),
                ('retry_count', models.SmallIntegerField(default=0)),
                ('retry_success', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
