# Generated by Django 4.2 on 2023-12-25 18:21

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import modelcluster.fields
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0001_initial"),
        ("wagtaildocs", "0012_uploadeddocument"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogCreateTask",
            fields=[
                (
                    "task_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "카탈로그 생성 작업",
                "verbose_name_plural": "카탈로그 생성 작업",
            },
            bases=("wagtailcore.task",),
        ),
        migrations.CreateModel(
            name="CatalogCreateTaskState",
            fields=[
                (
                    "taskstate_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.taskstate",
                    ),
                ),
            ],
            options={
                "verbose_name": "카탈로그 생성 작업 상태",
                "verbose_name_plural": "카탈로그 생성 작업 상태",
            },
            bases=("wagtailcore.taskstate",),
        ),
        migrations.CreateModel(
            name="CatalogSite",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            (
                                "image",
                                wagtail.images.blocks.ImageChooserBlock(
                                    label="이미지", required=False
                                ),
                            ),
                            (
                                "richtext",
                                wagtail.blocks.RichTextBlock(
                                    label="텍스트", required=False
                                ),
                            ),
                            (
                                "embed",
                                wagtail.embeds.blocks.EmbedBlock(
                                    label="임베드", required=False
                                ),
                            ),
                            (
                                "html",
                                wagtail.blocks.RawHTMLBlock(
                                    label="HTML", required=False
                                ),
                            ),
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                        verbose_name="콘텐츠",
                    ),
                ),
            ],
            options={
                "verbose_name": "카탈로그 사이트",
                "verbose_name_plural": "카탈로그 사이트",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="CatalogCreator",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True,
                        default="default",
                        max_length=255,
                        null=True,
                        verbose_name="테마",
                    ),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="공개")),
                (
                    "dpi",
                    models.IntegerField(
                        choices=[(150, "저화질"), (300, "일반 화질"), (600, "고화질")],
                        default=300,
                        verbose_name="pdf 해상도",
                    ),
                ),
                (
                    "image_page",
                    wagtail.fields.StreamField(
                        [
                            (
                                "image_page",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                help_text="목차에 표시될 페이지 제목",
                                                label="페이지 제목",
                                            ),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                help_text="300dpi A4 사이즈: 2481x3507 픽셀, 600dpi A4 사이즈: 4962x7014 픽셀",
                                                label="페이지 이미지",
                                            ),
                                        ),
                                        (
                                            "insert_to",
                                            wagtail.blocks.IntegerBlock(
                                                label="삽입할 위치 페이지 번호"
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                        verbose_name="이미지 페이지 삽입",
                    ),
                ),
                (
                    "page_logo",
                    wagtail.fields.StreamField(
                        [
                            (
                                "catalog_page_logo",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                help_text="300dpi 세로 1cm 사이즈: 118 픽셀, 600dpi 세로 1cm 사이즈: 236 픽셀",
                                                label="페이지 로고 이미지",
                                            ),
                                        ),
                                        (
                                            "apply_to_pages",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("odd", "홀수 페이지"),
                                                    ("even", "짝수 페이지"),
                                                    ("all", "모든 페이지"),
                                                ],
                                                label="적용할 페이지",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "apply_to_specific_pages",
                                            wagtail.blocks.CharBlock(
                                                help_text="ex. 11, 23, 22",
                                                label="적용할 특정 페이지",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                        verbose_name="페이지 로고",
                    ),
                ),
                (
                    "page_background",
                    wagtail.fields.StreamField(
                        [
                            (
                                "catalog_page_background",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                help_text="300dpi A4 사이즈: 2481x3507 픽셀, 600dpi A4 사이즈: 4962x7014 픽셀",
                                                label="페이지 배경 이미지",
                                            ),
                                        ),
                                        (
                                            "apply_to_pages",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("odd", "홀수 페이지"),
                                                    ("even", "짝수 페이지"),
                                                    ("all", "모든 페이지"),
                                                ],
                                                label="적용할 페이지",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "apply_to_specific_pages",
                                            wagtail.blocks.CharBlock(
                                                help_text="ex. 11, 23, 22",
                                                label="적용할 특정 페이지",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                        verbose_name="페이지 배경",
                    ),
                ),
                (
                    "attach_contents_page",
                    models.BooleanField(default=True, verbose_name="목차 페이지 첨부"),
                ),
                (
                    "course_sort",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="과정 정렬"
                    ),
                ),
                (
                    "exclude_tag_names",
                    models.CharField(
                        blank=True,
                        help_text="표시하지 않을 태그를 쉼표로 분리해서 입력하세요. 태그 표시만 숨깁니다.",
                        max_length=255,
                        null=True,
                        verbose_name="태그 숨기기",
                    ),
                ),
                ("css", models.TextField(blank=True, null=True, verbose_name="CSS")),
                (
                    "courses",
                    modelcluster.fields.ParentalManyToManyField(
                        related_name="+", to="course.course", verbose_name="과정"
                    ),
                ),
                (
                    "files",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True,
                        related_name="+",
                        to="wagtaildocs.document",
                        verbose_name="카탈로그 파일",
                    ),
                ),
            ],
            options={
                "verbose_name": "카탈로그",
                "verbose_name_plural": "카탈로그",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
