# Generated by Django 4.2 on 2024-01-02 02:04

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtaildocs", "0012_uploadeddocument"),
        ("catalog", "0001_initial"),
        ("program", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogprogram",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="program.programpage"
            ),
        ),
        migrations.AddField(
            model_name="catalogpage",
            name="catalog_files",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                related_name="+",
                to="wagtaildocs.document",
                verbose_name="카탈로그 파일",
            ),
        ),
    ]
