# Generated by Django 4.2 on 2024-01-02 02:04

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0001_initial"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=255, unique=True, verbose_name="제목"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="설명"),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="활성")),
                (
                    "courseruns",
                    models.ManyToManyField(
                        blank=True, to="course.courserun", verbose_name="과정 회차"
                    ),
                ),
            ],
            options={
                "verbose_name": "컬렉션",
                "verbose_name_plural": "컬렉션",
            },
        ),
        migrations.CreateModel(
            name="CollectionEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                (
                    "start",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="시작"
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="종료"
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enrollment.collection",
                        verbose_name="컬렉션",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                        verbose_name="학습자",
                    ),
                ),
            ],
            options={
                "verbose_name": "컬렉션 등록",
                "verbose_name_plural": "컬렉션 등록",
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="수강 모드"
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="활성")),
                (
                    "study_start",
                    models.DateTimeField(blank=True, null=True, verbose_name="학습 시작"),
                ),
                (
                    "study_end",
                    models.DateTimeField(blank=True, null=True, verbose_name="학습 종료"),
                ),
                (
                    "review_period",
                    models.SmallIntegerField(default=0, verbose_name="복습 기간"),
                ),
                (
                    "courserun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.courserun",
                        verbose_name="과정 회차",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                        verbose_name="학습자",
                    ),
                ),
            ],
            options={
                "verbose_name": "수강",
                "verbose_name_plural": "수강",
                "unique_together": {("courserun", "student")},
            },
        ),
    ]
