# Generated by Django 4.2 on 2023-12-25 18:21

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import edx_operation.apps.core.utils.common
import edx_operation.apps.marketer.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("course", "0001_initial"),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseRunManaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "courserun",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.courserun",
                        verbose_name="회차",
                    ),
                ),
            ],
            options={
                "verbose_name": "담당 회차",
                "verbose_name_plural": "담당 회차",
            },
        ),
        migrations.CreateModel(
            name="CustomerManaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.customer",
                        verbose_name="고객사",
                    ),
                ),
            ],
            options={
                "verbose_name": "담당 고객사",
                "verbose_name_plural": "담당 고객사",
            },
        ),
        migrations.CreateModel(
            name="Marketer",
            fields=[],
            options={
                "verbose_name": "영업자",
                "verbose_name_plural": "영업자",
                "permissions": (("marketer", "영업자"),),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.user",),
            managers=[
                ("objects", edx_operation.apps.marketer.models.MarketerManager()),
                ("user_objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="MarketerInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                (
                    "contract",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=edx_operation.apps.core.utils.common.upload_unique_name,
                        verbose_name="계약서",
                    ),
                ),
                (
                    "courseruns",
                    models.ManyToManyField(
                        blank=True,
                        through="marketer.CourseRunManaging",
                        to="course.courserun",
                        verbose_name="담당 회차",
                    ),
                ),
                (
                    "customers",
                    models.ManyToManyField(
                        blank=True,
                        through="marketer.CustomerManaging",
                        to="customer.customer",
                        verbose_name="담당 고객사",
                    ),
                ),
                (
                    "marketer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketer.marketer",
                        verbose_name="영업자",
                    ),
                ),
            ],
            options={
                "verbose_name": "영업자 정보",
                "verbose_name_plural": "영업자 정보",
            },
        ),
        migrations.AddField(
            model_name="customermanaging",
            name="marketerinfo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="marketer.marketerinfo",
                verbose_name="영업자",
            ),
        ),
        migrations.AddField(
            model_name="courserunmanaging",
            name="marketerinfo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="marketer.marketerinfo",
                verbose_name="영업자",
            ),
        ),
    ]
