# Generated by Django 4.2 on 2024-01-02 02:04

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0001_initial"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="제목"
                    ),
                ),
                ("body", models.TextField(blank=True, null=True, verbose_name="내용")),
                (
                    "annoymous",
                    models.BooleanField(blank=True, null=True, verbose_name="익명"),
                ),
                (
                    "depth",
                    models.SmallIntegerField(blank=True, null=True, verbose_name="단계"),
                ),
                (
                    "commentable_id",
                    models.CharField(max_length=255, verbose_name="게시판 위치"),
                ),
                (
                    "thread_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="종류"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="생성"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="수정"),
                ),
                (
                    "closed",
                    models.BooleanField(blank=True, null=True, verbose_name="종료"),
                ),
                ("votes", models.JSONField(blank=True, null=True, verbose_name="추천")),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="형식"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(blank=True, null=True, verbose_name="삭제"),
                ),
                (
                    "courserun",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.courserun",
                        verbose_name="과정 회차",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="operation.post",
                        verbose_name="부모글",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                        verbose_name="학습자",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="operation.post",
                        verbose_name="쓰레드",
                    ),
                ),
            ],
            options={
                "verbose_name": "질문 답변",
                "verbose_name_plural": "질문 답변",
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "shut_downed",
                    models.BooleanField(default=False, verbose_name="운영 종료"),
                ),
                (
                    "courserun",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.courserun",
                        verbose_name="회차",
                    ),
                ),
            ],
            options={
                "verbose_name": "운영",
                "verbose_name_plural": "운영",
            },
        ),
        migrations.CreateModel(
            name="CourseRunAccessRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "org",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="분류",
                    ),
                ),
                (
                    "role",
                    models.CharField(db_index=True, max_length=64, verbose_name="권한"),
                ),
                (
                    "courserun",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.courserun",
                        verbose_name="회차",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                        verbose_name="학습자",
                    ),
                ),
            ],
            options={
                "verbose_name": "수강 권한",
                "verbose_name_plural": "수강 권한",
                "unique_together": {("org", "courserun", "student", "role")},
            },
        ),
    ]
