# Generated by Django 4.2 on 2023-12-25 18:21

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import edx_operation.apps.core.utils.common


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseAccredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "esimsa_code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        validators=[
                            edx_operation.apps.core.utils.common.Validator.validate_esimsa_code
                        ],
                        verbose_name="과정 승인 코드",
                    ),
                ),
                (
                    "esimsa_code_expiration",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="과정 승인 만료"
                    ),
                ),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.course",
                        verbose_name="과정",
                    ),
                ),
                (
                    "courserun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.courserun",
                        verbose_name="회차",
                    ),
                ),
            ],
            options={
                "verbose_name": "과정 승인",
                "verbose_name_plural": "과정 승인",
                "permissions": (("accredit_manager", "과정 승인 담당자"),),
            },
        ),
    ]
