# Generated by Django 4.2 on 2024-01-02 02:04

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import edx_operation.apps.core.utils.common
import wagtail.search.index


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("student", "0001_initial"),
        ("enrollment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=255, verbose_name="고객사"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="슬러그"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="",
                        verbose_name="로고",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="이메일"
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="규모"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="전화"
                    ),
                ),
                (
                    "fax",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="팩스"
                    ),
                ),
                (
                    "ceo_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="CEO"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="우편번호"
                    ),
                ),
                (
                    "business_registration_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="사업자등록번호",
                    ),
                ),
                (
                    "business_management_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="사업장관리번호",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=254, null=True, verbose_name="주소"
                    ),
                ),
                (
                    "pin_number",
                    models.CharField(
                        blank=True,
                        default=edx_operation.apps.core.utils.common.random_four_digit,
                        max_length=16,
                        null=True,
                        verbose_name="핀번호",
                    ),
                ),
            ],
            options={
                "verbose_name": "고객사",
                "verbose_name_plural": "고객사",
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name="CustomerStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="부서"
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="직위"
                    ),
                ),
                (
                    "job_responsibility",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="직책"
                    ),
                ),
                (
                    "occupation_type",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="고용 형태"
                    ),
                ),
                (
                    "working_type",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="근로 형태"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.customer",
                        verbose_name="고객사",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                        verbose_name="학습자",
                    ),
                ),
            ],
            options={
                "verbose_name": "고객사 학습자",
                "verbose_name_plural": "고객사 학습자",
                "unique_together": {("customer", "student")},
            },
        ),
        migrations.CreateModel(
            name="CustomerEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.customer",
                        verbose_name="고객사",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enrollment.enrollment",
                        verbose_name="수강",
                    ),
                ),
            ],
            options={
                "verbose_name": "고객사 수강",
                "verbose_name_plural": "고객사 수강",
                "unique_together": {("customer", "enrollment")},
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="enrollments",
            field=models.ManyToManyField(
                blank=True,
                through="customer.CustomerEnrollment",
                to="enrollment.enrollment",
                verbose_name="수강",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                through="customer.CustomerStudent",
                to="student.student",
                verbose_name="학습자",
            ),
        ),
    ]
