# Generated by Django 4.2 on 2024-01-02 02:04

from django.db import migrations, models
import django_extensions.db.fields
import edx_operation.apps.core.utils.common


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="사용자 이름",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="이매일"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="이름"
                    ),
                ),
                (
                    "year_of_birth",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            edx_operation.apps.core.utils.common.Validator.validate_year_of_birth
                        ],
                        verbose_name="생년월일",
                    ),
                ),
                (
                    "birthday",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            edx_operation.apps.core.utils.common.Validator.validate_birthday
                        ],
                        verbose_name="생년월일",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("f", "여성"), ("m", "남성"), ("o", "기타")],
                        max_length=10,
                        null=True,
                        verbose_name="성별",
                    ),
                ),
                (
                    "cellphone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        validators=[
                            edx_operation.apps.core.utils.common.Validator.validate_cellphone
                        ],
                        verbose_name="휴대폰",
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="주민등록번호"
                    ),
                ),
                (
                    "initial_password",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="패스워드"
                    ),
                ),
                (
                    "password_change_required",
                    models.BooleanField(default=False, verbose_name="패스워드 변경 안내"),
                ),
                (
                    "pin_number",
                    models.CharField(
                        blank=True,
                        default=edx_operation.apps.core.utils.common.random_four_digit,
                        max_length=16,
                        null=True,
                        verbose_name="핀번호",
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="활성")),
                (
                    "is_staff",
                    models.BooleanField(blank=True, null=True, verbose_name="스태프"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(blank=True, null=True, verbose_name="수퍼유저"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(blank=True, null=True, verbose_name="가입"),
                ),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="마지막 로그인"),
                ),
            ],
            options={
                "verbose_name": "학습자",
                "verbose_name_plural": "학습자",
            },
        ),
    ]
