# Generated by Django 4.2 on 2024-01-02 02:04

from django.db import migrations, models
import django.db.models.deletion
import hitcount.models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsHome",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(blank=True, null=True, verbose_name="간략한 설명"),
                ),
                (
                    "content",
                    wagtail.fields.RichTextField(
                        blank=True, null=True, verbose_name="내용"
                    ),
                ),
            ],
            options={
                "verbose_name": "뉴스",
                "verbose_name_plural": "뉴스",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NewsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            (
                                "richtext",
                                wagtail.blocks.RichTextBlock(
                                    label="에디터", required=False
                                ),
                            ),
                            (
                                "html",
                                wagtail.blocks.RawHTMLBlock(
                                    label="HTML 코드", required=False
                                ),
                            ),
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                        verbose_name="내용",
                    ),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="상단 정렬")),
                (
                    "external_link",
                    models.URLField(
                        blank=True, max_length=254, null=True, verbose_name="외부 링크"
                    ),
                ),
                (
                    "allow_comments",
                    models.BooleanField(default=True, verbose_name="댓글 사용하기"),
                ),
            ],
            options={
                "verbose_name": "뉴스",
                "verbose_name_plural": "뉴스",
            },
            bases=("wagtailcore.page", hitcount.models.HitCountMixin),
        ),
    ]
