# Generated by Django 4.2 on 2023-12-25 18:23

from django.db import migrations, models
import django.db.models.deletion
import edx_operation.apps.core.utils.common
import modelcluster.fields
import taggit.managers
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.search.index


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtail_common", "0001_initial"),
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(unique=True, verbose_name="제목")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                (
                    "sku",
                    models.CharField(
                        default=edx_operation.apps.core.utils.common.secure_redeem_code,
                        unique=True,
                        verbose_name="상품 코드",
                    ),
                ),
                (
                    "description",
                    wagtail.fields.StreamField(
                        [
                            (
                                "image",
                                wagtail.images.blocks.ImageChooserBlock(
                                    label="이미지", required=False
                                ),
                            ),
                            (
                                "richtext",
                                wagtail.blocks.RichTextBlock(
                                    label="텍스트", required=False
                                ),
                            ),
                            (
                                "embed",
                                wagtail.embeds.blocks.EmbedBlock(
                                    label="임베드", required=False
                                ),
                            ),
                            (
                                "html",
                                wagtail.blocks.RawHTMLBlock(
                                    help_text="html 코드를 입력할 수 있습니다.",
                                    label="HTML",
                                    required=False,
                                ),
                            ),
                        ],
                        use_json_field=True,
                        verbose_name="상품 소개",
                    ),
                ),
                (
                    "enrollment_days",
                    models.SmallIntegerField(default=0, verbose_name="수강 일 수"),
                ),
                ("price", models.PositiveBigIntegerField(default=0, verbose_name="가격")),
                (
                    "tuition_assistances",
                    wagtail.fields.StreamField(
                        [
                            (
                                "tuition_assistance",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "policy",
                                            wagtail.blocks.CharBlock(label="교육비 지원 제도"),
                                        ),
                                        (
                                            "assistance",
                                            wagtail.contrib.table_block.blocks.TableBlock(
                                                label="지원 내용"
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                        verbose_name="교육비 지원",
                    ),
                ),
                (
                    "tutor",
                    wagtail.fields.StreamField(
                        [
                            (
                                "tutor",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="사진", required=False
                                            ),
                                        ),
                                        ("name", wagtail.blocks.CharBlock(label="이름")),
                                        (
                                            "bio",
                                            wagtail.blocks.RichTextBlock(
                                                label="바이오", required=False
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                        verbose_name="교강사",
                    ),
                ),
                (
                    "textbook",
                    wagtail.fields.StreamField(
                        [
                            (
                                "textbook",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("title", wagtail.blocks.CharBlock(label="제목")),
                                        (
                                            "author",
                                            wagtail.blocks.CharBlock(label="저자"),
                                        ),
                                        (
                                            "publisher",
                                            wagtail.blocks.CharBlock(label="출판사"),
                                        ),
                                        (
                                            "published_date",
                                            wagtail.blocks.DateBlock(
                                                label="출간일", required=False
                                            ),
                                        ),
                                        (
                                            "isbn",
                                            wagtail.blocks.CharBlock(label="ISBN"),
                                        ),
                                        (
                                            "price",
                                            wagtail.blocks.IntegerBlock(label="가격"),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                        use_json_field=True,
                        verbose_name="교재",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, to="wagtail_common.category", verbose_name="카테고리"
                    ),
                ),
                (
                    "cover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="wagtail_common.Tagging",
                        to="wagtail_common.Tag",
                        verbose_name="태그",
                    ),
                ),
            ],
            options={
                "verbose_name": "과정 상품",
                "verbose_name_plural": "과정 상품",
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name="LmsCourse",
            fields=[],
            options={
                "verbose_name": "과정",
                "verbose_name_plural": "과정",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(wagtail.search.index.Indexed, "course.course"),
        ),
        migrations.CreateModel(
            name="RelatedCourseProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "product",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related",
                        to="course_product.courseproduct",
                    ),
                ),
                (
                    "related",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="course_product.courseproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductLmsCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="course_product.lmscourse",
                    ),
                ),
                (
                    "product",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="course_product.courseproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
